# Generated by Django 3.0.3 on 2020-02-16 03:24

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_id', models.AutoField(db_column='account_id', primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(db_column='userid', max_length=23, unique=True)),
                ('password', models.CharField(db_column='user_pass', max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('email', models.EmailField(max_length=39, unique=True)),
                ('group_id', models.IntegerField(blank=True, default=0)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Active'), (1, 'Banned')], default=0)),
                ('unban_time', models.PositiveIntegerField(blank=True, default=0)),
                ('expiration_time', models.PositiveIntegerField(blank=True, default=0)),
                ('logincount', models.PositiveIntegerField(blank=True, default=0)),
                ('last_ip', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(default='2020-01-01', null=True)),
                ('character_slots', models.PositiveIntegerField(default=12)),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('pincode_change', models.PositiveIntegerField(blank=True)),
                ('vip_time', models.PositiveIntegerField(blank=True, default=0)),
                ('old_group', models.IntegerField(blank=True, default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'login',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
